# Este es el archivo de configuración corregido para Netlify.

[build]
  # Directorio base donde se encuentra la herramienta de IA.
  base = "herramienta-ia-netlify"
  
  # El directorio a publicar es el mismo directorio base.
  publish = "." 
  
  # El directorio de las funciones seguras.
  functions = "netlify/functions"

