# Archivo de configuración para Netlify (Versión corregida)

[build]
  # Directorio que Netlify debe desplegar.
  publish = "."

[functions]
  # Directorio donde Netlify debe buscar tus funciones de servidor.
  # Esta es la única línea necesaria para definir la carpeta.
  directory = "netlify/functions"
  node_bundler = "zisi"

[lfs]
  fetch_deep = true
